// bot_frontend/src/config/chatConfig.js
export const commands = [
    { command: "/create", description: "Start a new project" },
    { command: "/projects", description: "List your projects" },
    { command: "/download", description: "Grab your latest file" },
    { command: "/reset_name", description: "Change your name" },
    { command: "/tone", description: "Set my vibe (e.g., /tone sassy)" },
    { command: "/guide", description: "See all commands" },
  ];
  
  export const colorSchemes = {
    neon: {
      bg: "bg-gray-900",
      chatBg: "bg-gray-800",
      text: "text-gray-300",
      user: "text-neon-yellow bg-gray-700 shadow-lg border-2 border-neon-yellow rounded-lg p-2",
      bot: "text-neon-green bg-gray-800",
      system: "text-neon-blue bg-gray-900 italic",
      command: "text-neon-purple bg-gray-700",
      success: "text-neon-green bg-gray-800",
      error: "text-neon-red bg-gray-800",
      question: "text-[#ADD8E6] bg-gray-800",
      progress: "bg-gray-800",
      download: "bg-purple-900 text-purple-200",
      button: "bg-neon-green hover:bg-neon-yellow",
      buttonText: "text-gray-900",
      accent: "text-neon-yellow",
      bubble: "bg-purple-600 hover:bg-yellow-400 text-white font-semibold",
    },
    cyberpunk: {
      bg: "bg-cyber-dark",
      chatBg: "bg-gray-900",
      text: "text-cyber-cyan",
      user: "text-cyber-pink bg-gray-900 border-2 border-cyber-pink rounded-lg p-2 shadow-cyber animate-glow",
      bot: "text-cyber-cyan bg-gray-900",
      system: "text-cyber-purple bg-cyber-dark italic",
      command: "text-white bg-gray-900",
      success: "text-cyber-cyan bg-gray-900",
      error: "text-neon-red bg-gray-900",
      question: "text-cyber-cyan bg-gray-900",
      progress: "bg-gray-900",
      download: "bg-cyber-purple text-cyber-cyan",
      button: "bg-cyber-cyan hover:bg-neon-blue",
      buttonText: "text-cyber-dark",
      accent: "text-cyber-pink",
      bubble: "bg-cyber-cyan hover:bg-cyber-pink text-cyber-dark font-semibold",
    },
    retro: {
      bg: "bg-stone-200",
      chatBg: "bg-retro-dark",
      text: "text-retro-orange",
      user: "text-retro-orange bg-retro-dark border-2 border-retro-orange rounded-sm p-2 shadow-retro",
      bot: "text-retro-green bg-retro-dark",
      system: "text-retro-blue bg-stone-200 italic",
      command: "text-retro-blue bg-retro-dark",
      success: "text-retro-green bg-retro-dark",
      error: "text-neon-red bg-retro-dark",
      question: "text-retro-orange bg-retro-dark",
      progress: "bg-retro-dark",
      download: "bg-retro-green text-stone-200",
      button: "bg-retro-orange hover:bg-retro-orange",
      buttonText: "text-stone-900",
      accent: "text-retro-orange",
      bubble: "bg-retro-green hover:bg-retro-orange text-stone-900 font-semibold",
    },
    pastel: {
      bg: "bg-pastel-bg",
      chatBg: "bg-pastel-light",
      text: "text-pastel-dark",
      user: "text-pastel-pink bg-pastel-light border-2 border-pastel-pink rounded-lg p-2 shadow-pastel",
      bot: "text-pastel-blue bg-pastel-light",
      system: "text-pastel-purple bg-pastel-bg italic",
      command: "text-pastel-teal bg-pastel-light",
      success: "text-pastel-blue bg-pastel-light",
      error: "text-neon-red bg-pastel-light",
      question: "text-pastel-dark bg-pastel-light",
      progress: "bg-pastel-light",
      download: "bg-pastel-blue text-pastel-bg",
      button: "bg-pastel-pink hover:bg-pastel-teal",
      buttonText: "text-pastel-dark",
      accent: "text-pastel-pink",
      bubble: "bg-pastel-blue hover:bg-pastel-teal text-pastel-dark font-semibold",
    },
    matrix: {
      bg: "bg-matrix-dark",
      chatBg: "bg-matrix-bg",
      text: "text-matrix-green",
      user: "text-matrix-green bg-matrix-bg border-2 border-matrix-green rounded-sm p-2 animate-matrix-glitch font-mono",
      bot: "text-matrix-green bg-matrix-bg",
      system: "text-neon-blue bg-matrix-bg italic",
      command: "text-neon-purple bg-matrix-bg",
      success: "text-matrix-green bg-matrix-bg",
      error: "text-neon-red bg-matrix-bg",
      question: "text-matrix-green bg-matrix-bg",
      progress: "bg-matrix-bg",
      download: "bg-matrix-green text-matrix-dark",
      button: "bg-matrix-green hover:bg-neon-blue",
      buttonText: "text-matrix-dark",
      accent: "text-matrix-green",
      bubble: "bg-matrix-green hover:bg-neon-blue text-matrix-dark font-semibold",
    },
  };