services:
  bot_frontend:
    build:
      context: ./bot_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - bot_network
    depends_on:
      - websocket_server
      - bot_lead
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot_backend:
    build:
      context: ./bot_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - bot_network
    depends_on:
      - websocket_server
      - redis
    command: node src/server.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot_lead:
    build:
      context: ./bot_lead
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - bot_network
    depends_on:
      - websocket_server
    environment: {}
    command: pm2-runtime start src/ecosystem.config.cjs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  websocket_server:
    build:
      context: ./websocket_server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5002"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    environment: {}

  ngrok:
    image: ngrok/ngrok
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: ["start", "--config", "/etc/ngrok.yml", "--all"]
    ports:
      - "4040:4040"
    networks:
      - bot_network
    depends_on:
      - bot_frontend
      - bot_backend
      - websocket_server
      - bot_lead

networks:
  bot_network:
    driver: bridge