import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const JSZip = require('jszip');

export async function zipFilesWithReadme(files, task) {
  const zip = new JSZip();
  for (const [fileName, content] of Object.entries(files)) {
    if (typeof content === 'string' || Buffer.isBuffer(content)) {
      zip.file(fileName, content);
    } else {
      console.error(`Skipping invalid file content for "${fileName}": ${JSON.stringify(content)}`);
    }
  }
  const readme = `<html><body><h1>${task.name}</h1><p>Features: ${task.features}</p><footer>Generated by Cracker Bot - <a href="https://github.com/chefken052580/cracker-bot">GitHub</a></footer></body></html>`;
  zip.file('readme.html', readme);
  return await zip.generateAsync({ type: "nodebuffer" }); // Match taskExecution.js expectation
}