// ai_coders/bot_backend/src/contentUtils.js
import JSZip from 'jszip'; // ESM import
import { log, error } from './logger.js';

export async function zipFilesWithReadme(files, task) {
  const zip = new JSZip();
  let validFilesAdded = 0;
  const invalidFiles = [];

  // Validate files input
  if (!files || typeof files !== 'object' || Object.keys(files).length === 0) {
    await error(`No files provided to zip for task "${task.taskId || 'unknown'}"`);
    throw new Error('No files provided to zip');
  }

  // Process each file
  for (const [fileName, content] of Object.entries(files)) {
    if (typeof fileName !== 'string' || !fileName.trim()) {
      invalidFiles.push({ fileName: fileName || 'unnamed', reason: 'Invalid or empty file name' });
      await error(`Invalid file name "${fileName}" in task "${task.taskId || 'unknown'}"`);
      continue;
    }

    if (typeof content === 'string') {
      try {
        zip.file(fileName, Buffer.from(content, 'base64')); // Decode base64 to raw content
        validFilesAdded++;
      } catch (e) {
        invalidFiles.push({ fileName, reason: `Failed to decode base64: ${e.message}` });
        await error(`Failed to decode base64 content for "${fileName}" in task "${task.taskId || 'unknown'}": ${e.message}`);
      }
    } else if (Buffer.isBuffer(content)) {
      zip.file(fileName, content);
      validFilesAdded++;
    } else {
      invalidFiles.push({ fileName, reason: `Invalid content type: ${typeof content}` });
      await error(`Skipping invalid file content for "${fileName}" in task "${task.taskId || 'unknown'}": ${typeof content}`);
    }
  }

  if (validFilesAdded === 0) {
    const errorMsg = `No valid files to zip for task "${task.taskId || 'unknown'}". Invalid files: ${JSON.stringify(invalidFiles)}`;
    await error(errorMsg);
    throw new Error(errorMsg);
  }

  // Generate enhanced readme with flair
  const taskName = task.name || 'Untitled Task';
  const taskFeatures = task.features || 'No features specified';
  const isGame = task.features?.toLowerCase().includes('game') || task.type === 'full-stack';
  const readmeContent = `
<html>
  <head>
    <title>${taskName} - Cracker Bot Creation</title>
    <style>
      body { font-family: Arial, sans-serif; background: #1a1a1a; color: #00ff00; padding: 20px; }
      h1 { font-size: 2em; text-shadow: 0 0 5px #00ff00; }
      p { line-height: 1.6; }
      footer { margin-top: 20px; font-size: 0.9em; color: #00cc00; }
      a { color: #00ff99; text-decoration: none; }
      a:hover { text-decoration: underline; }
    </style>
  </head>
  <body>
    <h1>${taskName}</h1>
    <p>Welcome to your Cracker Bot masterpiece! This ZIP contains everything you need to rock this project.</p>
    <h2>Features</h2>
    <p>${taskFeatures.replace(/, /g, '<br>')}</p>
    <h2>How to Run</h2>
    <p>
      ${isGame ? 
        'Unzip this folder and double-click <strong>index.html</strong> to launch in your browser. For Windows, use <strong>run.bat</strong> if included for a quick start!' : 
        'Unzip and check the files—open them in your favorite editor or run them as needed. Cracker Bot’s got your back!'}
    </p>
    <footer>
      Generated by Cracker Bot - <a href="https://github.com/chefken052580/cracker-bot">GitHub</a><br>
      Timestamp: ${new Date().toISOString()} - Keep it slick, fam!
    </footer>
  </body>
</html>`;
  zip.file('readme.html', readmeContent);

  // Add Windows run script for games or full-stack projects
  if (isGame) {
    const runBat = `@echo off\r\nstart "" "index.html"\r\necho Launched ${taskName} - Enjoy!\r\npause`;
    zip.file('run.bat', runBat);
  }

  try {
    const buffer = await zip.generateAsync({ type: "nodebuffer" });
    await log(`Generated zip for task "${task.taskId || 'unknown'}" (${taskName}) with files: ${Object.keys(files).join(', ')}`);
    return buffer;
  } catch (e) {
    const errorMsg = `Failed to generate zip for task "${task.taskId || 'unknown'}": ${e.message}. Invalid files: ${JSON.stringify(invalidFiles)}`;
    await error(errorMsg);
    
    // Fallback: Return first valid file if possible
    if (validFilesAdded > 0) {
      const firstValidFile = Object.entries(files).find(([_, content]) => typeof content === 'string' || Buffer.isBuffer(content));
      if (firstValidFile) {
        await log(`Falling back to single file "${firstValidFile[0]}" for task "${task.taskId || 'unknown'}"`);
        return typeof firstValidFile[1] === 'string' ? Buffer.from(firstValidFile[1], 'base64') : firstValidFile[1];
      }
    }
    throw new Error(errorMsg);
  }
}