import { createRequire } from 'module';
import { log, error } from './logger.js';

const require = createRequire(import.meta.url);
let JSZip;
try {
  JSZip = require('jszip');
} catch (e) {
  console.error(`[${new Date().toISOString()}] Failed to load jszip: ${e.message}`);
  await error(`Failed to load jszip: ${e.message}`); // Await error log
  process.exit(1);
}

export async function zipFilesWithReadme(files, task) {
  const zip = new JSZip();
  let validFilesAdded = 0;

  // Validate files input
  if (!files || typeof files !== 'object' || Object.keys(files).length === 0) {
    await error(`No files provided to zip for task "${task.taskId || 'unknown'}"`);
    throw new Error('No files provided to zip');
  }

  for (const [fileName, content] of Object.entries(files)) {
    if (typeof fileName !== 'string' || !fileName.trim()) {
      await error(`Invalid file name "${fileName}" in task "${task.taskId || 'unknown'}"`);
      continue;
    }

    if (typeof content === 'string') {
      try {
        zip.file(fileName, Buffer.from(content, 'base64')); // Decode base64 to raw content
        validFilesAdded++;
      } catch (e) {
        await error(`Failed to decode base64 content for "${fileName}" in task "${task.taskId || 'unknown'}": ${e.message}`);
      }
    } else if (Buffer.isBuffer(content)) {
      zip.file(fileName, content);
      validFilesAdded++;
    } else {
      await error(`Skipping invalid file content for "${fileName}" in task "${task.taskId || 'unknown'}": ${typeof content}`);
    }
  }

  if (validFilesAdded === 0) {
    await error(`No valid files to zip for task "${task.taskId || 'unknown'}"`);
    throw new Error(`No valid files to zip for task "${task.taskId || 'unknown'}"`);
  }

  const taskName = task.name || 'Untitled Task';
  const taskFeatures = task.features || 'No features specified';
  const readme = `<html><body><h1>${taskName}</h1><p>Features: ${taskFeatures}</p><footer>Generated by Cracker Bot - <a href="https://github.com/chefken052580/cracker-bot">GitHub</a></footer></body></html>`;
  zip.file('readme.html', readme);

  try {
    const buffer = await zip.generateAsync({ type: "nodebuffer" });
    await log(`Generated zip for task "${task.taskId || 'unknown'}" (${taskName}) with files: ${Object.keys(files).join(', ')}`);
    return buffer;
  } catch (e) {
    await error(`Failed to generate zip for task "${task.taskId || 'unknown'}": ${e.message}`);
    throw e;
  }
}